# Generated by Django 5.0.3 on 2024-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
