# Generated by Django 5.0.3 on 2024-07-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
